language: python
python:
  - "3.6"
  - "3.6-dev"  # 3.6 development branch
  - "3.7-dev"  # 3.7 development branch
  - "3.8"

before_install:
  - cd python
install:
  - pip install -r requirements.txt
script:
  - pytest python/2017
  - pytest python/2018
